---

- get_url:
    url: "{{ jumpcloud_installer_url }}"
    headers: "x-connect-key:{{ jumpcloud_connect_key }}"
    dest: /tmp/jc.install.sh
    mode: 0775
  register: jcagent_result
  tags: jcagent

- shell:
    /tmp/jc.install.sh
  become: yes
  become_user: root
  tags: jcagent
