---

- name: make sure jumpcloud agent is started
  service:
    name: jcagent
    state: started
  ignore_errors: true
  become: yes

- name: get JumpCloud SystemKey
  command: grep -o -P '(?<=systemKey\":\")[a-zA-Z0-9]*' /opt/jc/jcagent.conf
  register: jumpcloud_system_key
  become: yes

- command: hostname
  register: hostname

- set_fact: 
    actual_hostname: "{{hostname.stdout}}"

- name: update system information
  uri:
    url: "{{ jumpcloud_api_v1_url }}/systems/{{ jumpcloud_system_key.stdout }}"
    method: PUT
    headers:
      "Content-Type": "application/json"
      "Accept":       "application/json"
      "x-api-key":    "{{ jumpcloud_api_key }}"
    body_format:  json
    body: '{ "displayName" : "{{ actual_hostname }}",
    "allowPublicKeyAuthentication" : "{{ jumpcloud_allowPublicKeyAuthentication }}",
    "allowSshPasswordAuthentication" : "{{ jumpcloud_allowSshPasswordAuthentication }}",
    "allowSshRootLogin" : "{{ jumpcloud_allowSshRootLogin }}",
    "allowMultiFactorAuthentication" : "{{ jumpcloud_allowMultiFactorAuthentication }}" }'
    follow_redirects: all
    return_content: yes
    status_code: 200
  delegate_to: localhost
  register: http_outcome
  when: jumpcloud_system_key is defined

- name: retrive system groups attributes based on the system group name
  uri:
    url: "{{ jumpcloud_api_v2_url }}/systemgroups?filter=name:eq:{{ item }}"
    method: GET
    headers:
      "Content-Type": "application/json"
      "Accept":       "application/json"
      "x-api-key":    "{{ jumpcloud_api_key }}"
    follow_redirects: all
    return_content: yes
  with_items: "{{ jumpcloud_system_groups }}"
  delegate_to: localhost
  register:  jc_system_groups_json_response
  ignore_errors: yes
  when: jumpcloud_system_key is defined and jumpcloud_system_groups is defined

- name: create the list of system groups attributes
  set_fact: jc_system_groups={{ jc_system_groups|default([]) | union(item.json) }}
  with_items: "{{ jc_system_groups_json_response.results}}"
  delegate_to: localhost

- name: add system to group(s)
  uri:
    url: "{{ jumpcloud_api_v2_url }}/systemgroups/{{ item.id }}/members"
    method: POST
    headers:
      "Content-Type": "application/json"
      "Accept":       "application/json"
      "x-api-key":    "{{ jumpcloud_api_key }}"
    body_format:  json
    body: '{ "op": "add","type": "system", "id": "{{ jumpcloud_system_key.stdout }}" }'
    follow_redirects: all
    return_content: yes
    # 204 = Successfully added, 409 = Already member
    status_code: 204,409
  with_items: "{{ jc_system_groups }}"
  delegate_to: localhost
  register: http_outcome
  ignore_errors: yes
  when: jumpcloud_system_key is defined and jc_system_groups is defined
